name: Build release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download keystore
      env:
        KEYSTORE_URL: ${{ secrets.keystoreURL }}
      run: ./tools/download_keystore.sh
    - name: Cache Gradle downloads
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build with Gradle
      env:
        KEYSTORE: signing.keystore
        KEY_ALIAS: mykey
        KEY_PASSWORD: ${{ secrets.keystorePassword }}
        KEYSTORE_PASSWORD: ${{ secrets.keystorePassword }}
      run: ./gradlew assembleRelease
    - name: Upload release APK
      uses: actions/upload-artifact@v1
      with:
        name: Release APK
        path: app/build/outputs/apk/release/app-release.apk
    - name: Extract release names
      run: ./tools/extract_release_names.sh
    - name: Create release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: $(cat ${GITHUB_WORKSPACE}/versionCode.txt)
        release_name: $(cat ${GITHUB_WORKSPACE}/versionName.txt)
        body: To see the changes, see the changes between https://github.com/zond/android-diplicity/commit/${GITHUB_SHA} and the previous release.
