name: Build release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: '1.14'
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download keystore
      env:
        KEYSTORE_URL: ${{ secrets.keystoreURL }}
      run: ./tools/download_keystore.sh
    - name: Cache Gradle downloads
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build with Gradle
      env:
        KEYSTORE: signing.keystore
        KEY_ALIAS: mykey
        KEY_PASSWORD: ${{ secrets.keystorePassword }}
        KEYSTORE_PASSWORD: ${{ secrets.keystorePassword }}
      run: ./gradlew assembleRelease
    - name: Publish release
      run: ./tools/create_release.sh

